In [3]:
import pandas as pd
df = pd.read_csv('/Users/prashanthrapaka/Downloads/playtennis.csv')
df

    Day   Outlook Temperature Humidity    Wind PlayTennis
0    D1     Sunny         Hot     High    Weak         No
1    D2     Sunny         Hot     High  Strong         No
2    D3  Overcast         Hot     High    Weak        Yes
3    D4      Rain        Mild     High    Weak        Yes
4    D5      Rain        Cool   Normal    Weak        Yes
5    D6      Rain        Cool   Normal  Strong         No
6    D7  Overcast        Cool   Normal  Strong        Yes
7    D8     Sunny        Mild     High    Weak         No
8    D9     Sunny        Cool   Normal    Weak        Yes
9   D10      Rain        Mild   Normal    Weak        Yes
10  D11     Sunny        Mild   Normal  Strong        Yes
11  D12  Overcast        Mild     High  Strong        Yes
12  D13  Overcast         Hot   Normal    Weak        Yes
13  D14      Rain        Mild     High  Strong         No

In [13]:
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()

# label encoding to categorical columns
df['Outlook'] = label_encoder.fit_transform(df['Outlook'])
df['Temperature'] = label_encoder.fit_transform(df['Temperature'])
df['Humidity'] = label_encoder.fit_transform(df['Humidity'])
df['Wind'] = label_encoder.fit_transform(df['Wind'])
df

    Day  Outlook  Temperature  Humidity  Wind PlayTennis
0    D1        2            1         0     1         No
1    D2        2            1         0     0         No
2    D3        0            1         0     1        Yes
3    D4        1            2         0     1        Yes
4    D5        1            0         1     1        Yes
5    D6        1            0         1     0         No
6    D7        0            0         1     0        Yes
7    D8        2            2         0     1         No
8    D9        2            0         1     1        Yes
9   D10        1            2         1     1        Yes
10  D11        2            2         1     0        Yes
11  D12        0            2         0     0        Yes
12  D13        0            1         1     1        Yes
13  D14        1            2         0     0         No